#!/usr/bin/env python3
"""Check or write the data files in supporting-material/machine-readable/.

For each guide (gpg-45 and gpg-44) this tool writes three files from the
repository's own text, so they cannot drift from it:

    predefined-values.csv    the table in schema-1.0/<guide>/05-predefined-values.md
    predefined-lists.csv     the table in schema-1.0/<guide>/06-predefined-lists.md
    data-dictionary.yaml     the same rows as data-dictionary.csv, grouped by element

The two CSV files copy the published tables cell for cell, with the
published column headings.

data-dictionary.csv is written by hand, because its descriptions are short
summaries that are not in the data schema. The tool does not write it. It
checks that the file lists exactly the elements, sub-elements and types
shown in the examples in schema-1.0/<guide>/03-data-model.md, in the same
order.

Usage:
    python tools/machine_readable.py            report problems (same as --check)
    python tools/machine_readable.py --check    report problems; exit 1 if any
    python tools/machine_readable.py --write    write the three generated files for each guide
"""

from __future__ import annotations

import argparse
import csv
import io
import json
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
GUIDES = ("gpg-45", "gpg-44")
SCHEMA = "schema-1.0"
OUTPUT = "supporting-material/machine-readable"

EXAMPLE = re.compile(r'^<pre class="schema-example">\n(.*?)^</pre>', re.MULTILINE | re.DOTALL)
DELIMITER_ROW = re.compile(r"^\|(\s*:?-+:?\s*\|)+$")
CONTAINER = re.compile(r"^(object|array) \((.+)\)$")
PLAIN_YAML = re.compile(r"^[A-Za-z0-9_][A-Za-z0-9_.-]*$")
YAML_KEYWORDS = {"true", "false", "yes", "no", "on", "off", "null", "y", "n", "nan", "inf"}
YAML_HEADER = (
    "# Written by tools/machine_readable.py from data-dictionary.csv. Do not edit this file.\n"
    "# Not part of the published data schema. The descriptions are summaries, not the published wording.\n"
)


class SourceError(Exception):
    """A source file does not have the structure the tool expects."""


def markdown_tables(source: str) -> list[list[list[str]]]:
    """Every Markdown table in the text, as rows of cells. The first row is the column headings."""
    tables, rows = [], []
    for line in [*source.split("\n"), ""]:
        if line.startswith("|"):
            rows.append(line.strip())
            continue
        if len(rows) >= 2 and DELIMITER_ROW.match(rows[1]):
            table = []
            for row in rows[:1] + rows[2:]:
                cells = [c.strip().replace("\\|", "|") for c in re.split(r"(?<!\\)\|", row)[1:-1]]
                # A bold first cell marks a row heading. The bold markers are not part of the value.
                cells[0] = re.sub(r"^\*\*(.+)\*\*$", r"\1", cells[0])
                table.append(cells)
            tables.append(table)
        rows = []
    return tables


def only_table(root: Path, guide: str, name: str) -> list[list[str]]:
    path = root / SCHEMA / guide / name
    tables = markdown_tables(path.read_text(encoding="utf-8"))
    if len(tables) != 1:
        raise SourceError(f"{SCHEMA}/{guide}/{name}: expected one table, found {len(tables)}")
    width = len(tables[0][0])
    if any(len(row) != width for row in tables[0]):
        raise SourceError(f"{SCHEMA}/{guide}/{name}: a table row does not have {width} cells")
    return tables[0]


def to_csv(rows: list[list[str]]) -> str:
    out = io.StringIO()
    csv.writer(out, lineterminator="\n").writerows(rows)
    return out.getvalue()


def model_fields(source: str) -> list[tuple[str, str, str]]:
    """(element, sub-element, type) for every line of every example in a data model file."""
    fields = []
    for block in EXAMPLE.findall(source):
        element = None
        for line in block.rstrip("\n").split("\n"):
            text = re.sub(r"<[^>]+>", "", line)
            if not text.strip():
                continue
            if not text.startswith(" "):
                element = text.strip().rstrip(":")
                continue
            name, colon, kind = text.strip().partition(":")
            if element is None or not colon:
                raise SourceError(f"cannot read the example line {line!r}")
            fields.append((element, name.strip(), kind.strip()))
    return fields


def accepted_types(published: str) -> set[str]:
    """How data-dictionary.csv may show a published type: as written, or either half of 'object (name)'."""
    container = CONTAINER.match(published)
    return {published, *container.groups()} if container else {published}


def read_dictionary(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        expected = ["element", "sub_element", "type", "description", "source"]
        if reader.fieldnames != expected:
            raise SourceError(f"{path.name}: the first line must be {','.join(expected)}")
        return list(reader)


def dictionary_problems(rows: list[dict[str, str]], fields: list[tuple[str, str, str]]) -> list[str]:
    problems = []
    listed = [(row["element"], row["sub_element"]) for row in rows]
    modelled = [(element, name) for element, name, _ in fields]
    if listed != modelled:
        for pair in [p for p in modelled if p not in listed]:
            problems.append(f"{pair[0]}.{pair[1]} is in the data model but not in the file")
        for pair in [p for p in listed if p not in modelled]:
            problems.append(f"{pair[0]}.{pair[1]} is in the file but not in the data model")
        if not problems:
            problems.append("the rows are not in the same order as the data model")
        return problems
    for row, (element, name, kind) in zip(rows, fields):
        if row["type"] not in accepted_types(kind):
            problems.append(f"{element}.{name} has type {row['type']!r}; the data model says {kind!r}")
    return problems


def looks_like_a_number(value: str) -> bool:
    for parse in (float, lambda text: int(text, 0)):
        try:
            parse(value)
            return True
        except ValueError:
            pass
    return False


def yaml_scalar(value: str) -> str:
    """A YAML string. Simple names are written plainly; anything else is quoted so it is read back unchanged."""
    if PLAIN_YAML.match(value) and value.lower() not in YAML_KEYWORDS and not looks_like_a_number(value):
        return value
    return json.dumps(value, ensure_ascii=False)


def to_yaml(rows: list[dict[str, str]]) -> str:
    """The rows of data-dictionary.csv grouped by element."""
    lines, current = [YAML_HEADER.rstrip("\n")], None
    for row in rows:
        if row["element"] != current:
            current = row["element"]
            lines += ["", f"- element: {yaml_scalar(current)}", "  sub_elements:"]
        lines += [
            f"    - name: {yaml_scalar(row['sub_element'])}",
            f"      type: {yaml_scalar(row['type'])}",
            f"      description: {json.dumps(row['description'], ensure_ascii=False)}",
            f"      source: {yaml_scalar(row['source'])}",
        ]
    return "\n".join(lines) + "\n"


def build(root: Path, guide: str) -> tuple[dict[str, str], list[str]]:
    """The generated files for one guide as {file name: content}, and problems in the hand-written file."""
    folder = root / OUTPUT / guide
    rows = read_dictionary(folder / "data-dictionary.csv")
    fields = model_fields((root / SCHEMA / guide / "03-data-model.md").read_text(encoding="utf-8"))
    if not fields:
        raise SourceError(f"{SCHEMA}/{guide}/03-data-model.md: no examples found")
    generated = {
        "predefined-values.csv": to_csv(only_table(root, guide, "05-predefined-values.md")),
        "predefined-lists.csv": to_csv(only_table(root, guide, "06-predefined-lists.md")),
        "data-dictionary.yaml": to_yaml(rows),
    }
    return generated, dictionary_problems(rows, fields)


def report(rel: str, message: str) -> None:
    if os.environ.get("GITHUB_ACTIONS") == "true":
        print(f"::error file={rel}::{message}")
    else:
        print(f"ERROR: {rel}: {message}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Check or write the machine-readable data files.")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="report problems without changing files (default)")
    mode.add_argument("--write", action="store_true", help="write the generated files")
    parser.add_argument("--root", type=Path, default=REPO_ROOT, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    root = args.root.resolve()

    problems = written = files = 0
    for guide in GUIDES:
        try:
            generated, hand_written = build(root, guide)
        except (OSError, SourceError) as err:
            print(f"ERROR: {err}")
            return 2
        for message in hand_written:
            problems += 1
            report(f"{OUTPUT}/{guide}/data-dictionary.csv", message)
        for name, content in generated.items():
            files += 1
            path = root / OUTPUT / guide / name
            current = path.read_bytes() if path.is_file() else None
            if current == content.encode("utf-8"):
                continue
            if args.write:
                path.write_bytes(content.encode("utf-8"))
                written += 1
                print(f"written: {OUTPUT}/{guide}/{name}")
            else:
                problems += 1
                report(f"{OUTPUT}/{guide}/{name}",
                       "does not match the schema text; run 'python tools/machine_readable.py --write'")

    if args.write:
        print(f"\n{files} generated files checked, {written} written, {problems} problem(s) need a manual fix.")
    elif problems:
        print(f"\n{problems} problem(s) found.")
    else:
        print(f"{files} generated files match the schema text, and the hand-written files list every data model element.")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    sys.exit(main())
